logger:
  log_dir: 'logs/'
  log_clear_days: 30

data:
  path_video: 'data/videos'
  path_img: 'data/images'
  dict_json: 'dicts/json'
  dict_csv: 'dicts/csv'
  ytb_file: 'data/dicts/json/convert_image2ytb.json' 

clip:
  path_json: 'data/dicts/json/keyframes_id_search.json'
  path_bin: 'data/dicts/bin/faiss_CLIP_cosine.bin'

blip2:
  path_json: 'data/dicts/json/keyframes_id_search.json'
  path_bin: 'data/dicts/bin/faiss_BLIP2_cosine.bin'

internvideo2:
  path_json: 'data/dicts/json/keyframes_id_search.json'
  path_bin: 'data/dicts/bin/faiss_InternVideo2_cosine.bin'

ocr:
  path_json: 'data/dicts/json/keyframes_id_search_ocr.json'
  path_bin: 'data/dicts/bin/faiss_VN_OCR_cosine_hp.bin'
  path_txt: 'data/dicts/txt/info_ocr.txt'

asr:
  path_json: 'data/dicts/json/keyframes_id_search.json'
  path_bin: 'data/dicts/bin/faiss_VN_ASR_cosine_hp.bin'
  path_txt: 'data/dicts/txt/info_asr.txt'