logger:
  log_dir: 'logs/'
  log_clear_days: 30

data:
  path_video: 'data/videos'
  path_img: 'data/images'

clip:
  path_json: 'data/dicts/json/keyframes_id_search.json'
  path_bin: 'data/dicts/bin/faiss_CLIP_cosine.bin'

blip2:
  path_json: 'data/dicts/json/keyframes_id_search.json'
  path_bin: 'data/dicts/bin/faiss_BLIP2_cosine.bin'

internvideo2:
  path_json: 'data/dicts/json/keyframes_id_search_internVid2.json'
  path_bin: 'data/dicts/bin/faiss_InternVideo2_cosine.bin'

ocr:
  path_json: 'data/dicts/json/keyframes_id_search_ocr.json'
  path_bin: 'data/dicts/bin/faiss_BKAI_OCR_cosine.bin'
  path_txt: 'data/dicts/txt/info_ocr.txt'