python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L13 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L14 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L15 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L16 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L17 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L18 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L19 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L20 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L21 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L22 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L23 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
python impl_img2npy.py --i /media/hoangtv/"New Volume"/backup/data_aic2024/images/Keyframes_L24 --o /home/hoangtv/Desktop/Nhan_CDT/CERBERUS/research/Text_Video_Retrieval/data/dicts/npy/clip
